pipeline {
    agent any

    stages {
        stage('Clonar o Repositório') {
            steps {
                git(branch: 'main', url: 'https://github.com/Ieozin/ebac-cypress-samples-fork.git')
            }
        }
        stage('Instalar Dependências') {
            steps {
                sh 'npm install'
            }
        }
        stage('Executar Testes') {
            steps {
                sh 'NO_COLOR=1 npm run cy:run'
            }
        }
    }
}
