pipeline {
    agent any

    stages {
        stage('Clonar o Repositorio') {
            steps {
                git branch : 'main', url: 'https://github.com/Ieozin/ebac-cypress-samples-fork.git'
            }
        }
        stage('Instalar Dependencias') {
            setps {
                sh 'npm install'
            }
        }
        stage('Executar testes') {
            steps {
                sh 'NO_COLOR=1 npm run cy:run'
            }
        }
    }   
}